version: "3.9"

services:
  pimin-db:
    image: postgres:16
    container_name: pimin-db
    environment:
      POSTGRES_USER: pikmin
      POSTGRES_PASSWORD: pikmin
      POSTGRES_DB: pikmindb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -h 127.0.0.1 -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pikminapi:
    build:
      context: C:/Users/greni/OneDrive/Documentos/repos/PikminApi   # RUTA DE PROYECTO
      dockerfile: Dockerfile
    container_name: pikmin_api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pimin-db:5432/pikmindb
      SPRING_DATASOURCE_USERNAME: pikmin
      SPRING_DATASOURCE_PASSWORD: pikmin
      SERVER_PORT: 8081
    depends_on:
      pimin-db:
        condition: service_healthy
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  hydra:
    image: oryd/hydra:v2
    container_name: hydra
    command: serve all --dev
    environment:
      DSN: memory
      SECRETS_SYSTEM: "change-me-super-secret-32chars-minxxxxxxxxxxxx"
      URLS_SELF_ISSUER: http://localhost:4444/
      STRATEGIES_ACCESS_TOKEN: jwt
      LOG_LEAK_SENSITIVE_VALUES: "true"
    ports:
      - "4444:4444" # public
      - "4445:4445" # admin

  # Mongo para NintendoApi
  mongo:
    image: mongo:7
    container_name: nintendo_mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  # NintendoApi gRPC server
  nintendoapi:
    build:
      context: C:/Users/greni/OneDrive/Documentos/repos/nintendoapi   # AJUSTA esta ruta 
      dockerfile: Dockerfile
    container_name: nintendo_api
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      # Conexión a MongoDB dentro de la red de Docker
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB_NAME: nintendo_db
      MONGO_CONSOLES_COLLECTION: consoles

      # Configuración gRPC
      GRPC_HOST: 0.0.0.0
      GRPC_PORT: 50051
      LOG_LEVEL: INFO
    ports:
      - "50051:50051"

  # API REST piklopedia (SOAP + gRPC client)
  piklopedia-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: piklopedia_api
    environment:
      # SOAP hacia PikminApi
      PIKMIN_SOAP_BASE_URL: http://pikminapi:8081/ws

      # JWT validation contra Hydra
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://hydra:4444/.well-known/jwks.json

      # Puerto interno Spring
      SERVER_PORT: 8090

      # Config gRPC Nintendo (se usan en application.yml)
      NINTENDO_GRPC_HOST: nintendoapi
      NINTENDO_GRPC_PORT: 50051
    depends_on:
      pikminapi:
        condition: service_started
      hydra:
        condition: service_started
      nintendoapi:
        condition: service_started
    ports:
      - "8090:8090"

volumes:
  mongo_data:

networks:
  default:
    name: piknet
